[connections.supabase]
SUPABASE_URL = "https://twgycanimwbzpzauykmc.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3Z3ljYW5pbXdienB6YXV5a21jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMjcxMDMsImV4cCI6MjA2MTYwMzEwM30.L5ITWtCa4_mJxHYxFouV-hE9BMzy8syGV7pH8MbBcqE"
